name: Check GCP action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2.1.3"
        with:
          # <-- FULL provider resource name (must include numeric project number)
          workload_identity_provider: "projects/48994678794/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider"
          service_account: "iam-lab-7-target@gcp-labs-9necgia2.iam.gserviceaccount.com"
          create_credentials_file: true
          export_environment_variables: true
          access_token_scopes: "https://www.googleapis.com/auth/cloud-platform"
          cleanup_credentials: true

      - id: "gcloud"
        name: "gcloud and read secret"
        run: |-
          echo "creds: ${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set project gcp-labs-9necgia2
          # Use the generated key file
          gcloud auth activate-service-account --key-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth list
          # quick validation commands
          gcloud projects list --limit=5
          gcloud secrets list --project=gcp-labs-9necgia2
          gcloud secrets versions access latest --secret=flag_iam_lab_7 --project=gcp-labs-9necgia2
